name: CI/CD pipeline for Python microservice

on:
  push:
    branches:
      - main

jobs:
  install-pip-deps:
    runs-on: self-hosted
    steps:
      - name: Checkout CI/CD repo
        uses: actions/checkout@v4

      - name: Print installing message
        run: echo "Installing all required dependencies..."

      - name: Checkout python-greetings repo
        uses: actions/checkout@v4
        with:
          repository: mtararujs/python-greetings
          path: python-greetings

      - name: Install Python dependencies
        working-directory: python-greetings
        run: pip3 install -r requirements.txt

  deploy-to-dev:
    runs-on: self-hosted
    needs: install-pip-deps
    steps:
      - name: Checkout CI/CD repo
        uses: actions/checkout@v4

      - name: Print deployment message
        run: echo "Deploying to dev environment"

      - name: Checkout python-greetings repo
        uses: actions/checkout@v4
        with:
          repository: mtararujs/python-greetings
          path: python-greetings

      - name: Stop existing PM2 service (in case if such already exists)
        working-directory: python-greetings
        run: pm2 delete greetings-app-dev || true

      - name: Start app with PM2 on port 7001
        working-directory: python-greetings
        run: pm2 start app.py --name greetings-app-dev -- --port 7001
