name: CI/CD pipeline for Python microservice

on:
  push:
    branches:
      - main

jobs:
  install-pip-deps:
    runs-on: self-hosted
    steps:
      - name: Checkout CI/CD repo
        uses: actions/checkout@v4

      - name: Install Python dependencies
        uses: ./.github/actions/install-python-deps
        with:
         repo: mtararujs/python-greetings
         path: python-greetings

  deploy-to-dev:
    runs-on: self-hosted
    needs: install-pip-deps
    steps:
      - name: Deploy to dev using composite action
        uses: ./.github/actions/deploy
        with:
          repo: mtararujs/python-greetings
          path: python-greetings
          env: dev
          port: 7001

  tests-on-dev:
    runs-on: self-hosted
    needs: deploy-to-dev
    steps:
      - name: Run dev tests using composite action
        uses: ./.github/actions/run-tests
        with:
          repo: mtararujs/course-js-api-framework
          path: course-tests
          env: dev
  
  deploy-to-staging:
    runs-on: self-hosted
    needs: tests-on-dev
    steps:
      - name: Deploy to staging using composite action
        uses: ./.github/actions/deploy
        with:
          repo: mtararujs/python-greetings
          path: python-greetings
          env: staging
          port: 7002

  # tests-on-staging:
  #   runs-on: self-hosted
  #   needs: deploy-to-staging
  #   steps:
  #     - name: Run staging tests using composite action
  #       uses: ./.github/actions/run-tests
  #       with:
  #         repo: mtararujs/course-js-api-framework
  #         path: course-tests
  #         env: staging

  deploy-to-preprod:
    runs-on: self-hosted
    #needs: tests-on-staging
    steps:
      - name: Deploy to preprod using composite action
        uses: ./.github/actions/deploy
        with:
          repo: mtararujs/python-greetings
          path: python-greetings
          env: preprod
          port: 7003

  tests-on-preprod:
    runs-on: self-hosted
    needs: deploy-to-preprod
    steps:
      - name: Run preprod tests using composite action
        uses: ./.github/actions/run-tests
        with:
          repo: mtararujs/course-js-api-framework
          path: course-tests
          env: preprod

  deploy-to-prod:
    runs-on: self-hosted
    needs: tests-on-preprod
    steps:
      - name: Deploy to prod using composite action
        uses: ./.github/actions/deploy
        with:
          repo: mtararujs/python-greetings
          path: python-greetings
          env: prod
          port: 7004

  tests-on-prod:
    runs-on: self-hosted
    needs: deploy-to-prod
    steps:
      - name: Run prod tests using composite action
        uses: ./.github/actions/run-tests
        with:
          repo: mtararujs/course-js-api-framework
          path: course-tests
          env: prod